@startuml

title class diagram

namespace rc {
class basic_sticky_counter<unsigned integral> {
  --
+ increment_if_not_zero(): bool
+ decrement_then_is_zero(): bool
+ read(): rc_type
+ is_sticky_zero(): bool
+ is_recycled_zero(): bool
+ is_sticky_or_recycled_zero(): bool
+ recycle(): void
+ {static} max(): rc_type
}


class sticky_counter_guard<sticky counter> {
    --
    + swap() : void
    + decrement_then_is_zero(): bool
    + owns_count(): bool
}

sticky_counter_guard ..> basic_sticky_counter

class counter_guard<integral atomic variable> {
    --
    + swap() : void
}

}

@enduml
